# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a1710b07ad8edcf514f1156f8c83a377e964e33ad270db91a0c26e0c5ee639bcd344803d2ef26745a1c86b0a19e6c8469fcc2c50910b789051784ea313c1cf5

test:
  secret_key_base: 22c0b8005748c718cef52f3d0f79b6734da8913d1b5ac98343f9d484431d2a7e473936a5353e3b8e4990cd857625acab31676dee18b4cb3be324cc474e73725d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
